version: "3.3"
services:
  llava:
    environment:
      QUANTISATION: --load-4bit
    build:
      context: .
    ports:
      - "${HOST_API_PORT:-7860}:${API_PORT:-7860}"
      - 7861:10000
      - 7862:40000
    stdin_open: true
    tty: true
    volumes:
      - ../llava-v1.5-13b:/app/llava-v1.5-13b
      - ../clip-vit-large-patch14-336:/app/clip-vit-large-patch14-336
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
